import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { MMDLoader } from 'three/addons/loaders/MMDLoader.js';
import { OutlineEffect } from 'three/addons/effects/OutlineEffect.js';
import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
import { MMDPhysics } from 'three/addons/animation/MMDPhysics.js';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const BUILD_VERSION = 'v1.10.5';
$('#build-version').textContent = BUILD_VERSION;
const state = { models: [], active: null, mixers: [], duration: 0, elapsed: 0, playing: true, loop: true, outline: true, environment: null, environmentStrength: .65, assets: [], rigHandles: [], physics: false, physicsSettings: { stiffness: .5, damping: .2, gravity: 1, wind: 0, turbulence: 0, parts: { hair: true, cloth: true, body: true } }, skinSettings: { specular: .2, wetness: 0, roughnessMap: 1 } };
const clock = new THREE.Clock(), scene = new THREE.Scene(), canvas = $('#scene');
scene.background = new THREE.Color(0xf1ece5);
const camera = new THREE.PerspectiveCamera(38, innerWidth / innerHeight, .1, 1000); camera.position.set(8, 5.4, 12);
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1;
const effect = new OutlineEffect(renderer, { defaultThickness: .0028, defaultColor: [0.04, .05, .07], defaultAlpha: .7, defaultKeepAlive: true });
const pmrem = new THREE.PMREMGenerator(renderer); pmrem.compileEquirectangularShader();
const controls = new OrbitControls(camera, canvas); controls.target.set(0, 4, 0); controls.enableDamping = true; controls.dampingFactor = .06; controls.minPolarAngle = 0; controls.maxPolarAngle = Math.PI; controls.mouseButtons = { LEFT: THREE.MOUSE.PAN, MIDDLE: THREE.MOUSE.ROTATE, RIGHT: THREE.MOUSE.PAN }; controls.screenSpacePanning = true;
let blenderPan = null; canvas.addEventListener('pointerdown', e => { if (e.button !== 1 || !e.shiftKey) return; blenderPan = { x: e.clientX, y: e.clientY }; controls.enabled = false; e.preventDefault(); e.stopImmediatePropagation(); }, true); addEventListener('pointermove', e => { if (!blenderPan) return; const dx = e.clientX - blenderPan.x, dy = e.clientY - blenderPan.y, distance = camera.position.distanceTo(controls.target) * .0015; const right = new THREE.Vector3().setFromMatrixColumn(camera.matrix, 0), up = new THREE.Vector3().setFromMatrixColumn(camera.matrix, 1); camera.position.addScaledVector(right, -dx * distance).addScaledVector(up, dy * distance); controls.target.addScaledVector(right, -dx * distance).addScaledVector(up, dy * distance); blenderPan = { x: e.clientX, y: e.clientY }; }); addEventListener('pointerup', () => { if (blenderPan) { blenderPan = null; controls.enabled = true; } });
const transform = new TransformControls(camera, renderer.domElement); transform.setMode('translate'); transform.visible = false; transform.addEventListener('dragging-changed', e => controls.enabled = !e.value); scene.add(transform);
const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2();
const ammoReady = new Promise(resolve => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/three@0.166.1/examples/jsm/libs/ammo.wasm.js'; script.onload = async () => { try { const Ammo = await globalThis.Ammo(); globalThis.Ammo = Ammo; resolve(Ammo); } catch { resolve(null); } }; script.onerror = () => resolve(null); document.head.append(script); });
scene.add(new THREE.AmbientLight(0xfff3e2, .3));
const key = new THREE.DirectionalLight(0xffd7b0, 1.25); key.position.set(3, 4, 5); key.castShadow = true; key.shadow.mapSize.set(2048, 2048); key.shadow.camera.left = key.shadow.camera.bottom = -15; key.shadow.camera.right = key.shadow.camera.top = 15; key.shadow.bias = -0.00015; key.shadow.normalBias = 0.035; key.shadow.radius = 2; scene.add(key);
const fill = new THREE.DirectionalLight(0xffe6c7, .28); fill.position.set(-4, 3, -3); scene.add(fill);
const floor = new THREE.Mesh(new THREE.CircleGeometry(20, 64), new THREE.MeshStandardMaterial({ color: 0xe9e1d8, roughness: .82 })); floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor);
const grid = new THREE.GridHelper(32, 32, 0xc8b9ad, 0xd9cec4); grid.position.y = .012; scene.add(grid);
const textureManager = new THREE.LoadingManager();
textureManager.setURLModifier(request => { const clean = decodeURIComponent(request).replace(/\\/g, '/').replace(/^.*mmd\//, ''); const asset = state.assets.find(x => x.kind === 'texture' && (x.path.endsWith(clean) || clean.endsWith(x.path) || x.name === clean.split('/').pop())); return asset ? url(asset.file) : request; });
const loader = new MMDLoader(textureManager); loader.setResourcePath('mmd/');

function toast(text) { $('#toast').textContent = text; $('#toast').classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('#toast').classList.remove('show'), 2500); }
function ext(file) { return file.name.split('.').pop().toLowerCase(); }
function url(file) { return URL.createObjectURL(file); }
function setNotice(text = 'READY — LOCAL MODE') { $('#notice').textContent = text; }

const db = new Promise((resolve, reject) => { const req = indexedDB.open('mmd-lab-assets', 1); req.onupgradeneeded = () => req.result.createObjectStore('assets', { keyPath: 'id' }); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); });
async function dbCall(mode, work) { const database = await db; return new Promise((resolve, reject) => { const tx = database.transaction('assets', mode), request = work(tx.objectStore('assets')); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function saveAsset(file, kind, path = '') { const id = `${kind}:${file.name}:${file.size}:${file.lastModified}:${path}`; await dbCall('readwrite', store => store.put({ id, kind, name: file.name, path, file, savedAt: Date.now() })); return id; }
async function removeAsset(id) { await dbCall('readwrite', store => store.delete(id)); state.assets = state.assets.filter(x => x.id !== id); renderLibraries(); }
async function refreshAssets() { state.assets = await dbCall('readonly', store => store.getAll()); renderLibraries(); }

function assetRow(asset, action) { const row = document.createElement('div'); row.className = 'asset'; const open = document.createElement('button'); open.className = 'asset-open'; open.innerHTML = `<span>＋</span><div><b>${asset.name}</b><small>${asset.path || asset.kind.toUpperCase()}</small></div>`; open.onclick = action; const del = document.createElement('button'); del.className = 'asset-delete'; del.title = 'ライブラリから削除'; del.textContent = '×'; del.onclick = () => removeAsset(asset.id); row.append(open, del); return row; }
function renderLibraries() { const draw = (kind, target, count, message, action) => { const assets = state.assets.filter(x => x.kind === kind); $(count).textContent = assets.length; const root = $(target); root.innerHTML = ''; if (!assets.length) { root.innerHTML = `<div class="empty">${message}</div>`; return; } assets.forEach(asset => root.append(assetRow(asset, () => action(asset)))); };
  draw('model', '#model-library', '#model-library-count', 'モデルを追加すると<br/>ここから再読み込みできます', loadAssetModel);
  draw('motion', '#motion-library', '#motion-library-count', 'モーションを追加すると<br/>ここから適用できます', applyAssetMotion);
}
async function importAssets(files, loadImmediately = false) { const saved = []; for (const file of [...files]) { const suffix = ext(file); const kind = ['pmx', 'pmd'].includes(suffix) ? 'model' : ['vmd', 'vpd'].includes(suffix) ? 'motion' : ['png', 'jpg', 'jpeg', 'bmp', 'tga', 'dds', 'webp'].includes(suffix) ? 'texture' : null; if (!kind) continue; const id = await saveAsset(file, kind, file.webkitRelativePath || ''); saved.push({ id, kind, name: file.name, path: file.webkitRelativePath || '', file }); } await refreshAssets(); if (loadImmediately) { for (const asset of saved.filter(x => x.kind === 'model')) await loadModel(asset.file); for (const asset of saved.filter(x => x.kind === 'motion')) await applyMotion(asset.file); } return saved; }
async function loadAssetModel(asset) { await loadModel(asset.file); }
async function applyAssetMotion(asset) { await applyMotion(asset.file); }

function loadModel(file) { return new Promise(resolve => { setNotice('LOADING MODEL…'); loader.load(url(file), mesh => { mesh.name = file.name; mesh.frustumCulled = false; mesh.castShadow = mesh.receiveShadow = true; mesh.traverse(node => { if (!node.isMesh) return; node.frustumCulled = false; node.castShadow = node.receiveShadow = true; const original = Array.isArray(node.material) ? node.material : [node.material]; const repaired = original.map(material => { if (!material) return material; if (material.map) { material.side = THREE.DoubleSide; material.depthWrite = !material.transparent; material.alphaTest = Math.max(material.alphaTest || 0, .01); material.needsUpdate = true; return material; } const color = material.color?.clone?.() || new THREE.Color(0xc8c8c8); return new THREE.MeshBasicMaterial({ color, side: THREE.DoubleSide, transparent: false, opacity: 1, depthWrite: true }); }); node.material = Array.isArray(node.material) ? repaired : repaired[0]; }); const item = { mesh, file, name: file.name, phase: Math.random() * Math.PI * 2, base: mesh.position.clone(), physics: null }; mesh.position.x = state.models.length * 2.7; scene.add(mesh); state.models.push(item); applySkinShader(); setupRigHandles(item); setActive(item); frameModel(mesh); renderSceneModels(); setNotice(); toast(`${file.name} を読み込みました`); resolve(item); }, undefined, error => { console.error(error); setNotice(); toast(`${file.name} を読めませんでした。コンソールを確認してください`); resolve(null); }); }); }
function applyMotion(file) { const item = state.active; if (!item) { toast('先にモデルを選択してください'); return Promise.resolve(); } if (ext(file) === 'vpd') return new Promise(resolve => loader.loadVPD(url(file), false, pose => { loader.poseAsVpd(item.mesh, pose); toast(`VPD: ${file.name}`); resolve(); }, undefined, () => { toast('VPD の読み込みに失敗しました'); resolve(); }));
  return new Promise(resolve => loader.loadAnimation(url(file), item.mesh, clip => { const mixer = new THREE.AnimationMixer(item.mesh); const action = mixer.clipAction(clip).play(); action.setLoop(THREE.LoopRepeat, Infinity); state.mixers.push({ mixer, action, clip, mesh: item.mesh }); state.duration = Math.max(state.duration, clip.duration); toast(`VMD: ${file.name}`); resolve(); }, undefined, () => { toast('VMD の読み込みに失敗しました'); resolve(); })); }
function frameModel(mesh) { const box = new THREE.Box3().setFromObject(mesh), size = box.getSize(new THREE.Vector3()), center = box.getCenter(new THREE.Vector3()); controls.target.copy(center); camera.position.copy(center).add(new THREE.Vector3(size.y * .62, size.y * .28, size.y * 1.45)); controls.update(); }
function setActive(item) { state.active = item; renderSceneModels(); renderMorphs(); renderMaterials(); }
function setupRigHandles(item) { state.rigHandles.forEach(h => scene.remove(h)); state.rigHandles = []; const bones = []; item.mesh.traverse(x => { if (x.isBone) bones.push(x); }); const choose = [bones.find(x => /上半身|chest|spine/i.test(x.name)), bones.find(x => /腰|センター|hips|pelvis/i.test(x.name))].filter(Boolean); choose.forEach((bone, index) => { const handle = new THREE.Mesh(new THREE.SphereGeometry(.16, 16, 12), new THREE.MeshBasicMaterial({ color: index ? 0x2a7de1 : 0xe15c2a, depthTest: false })); handle.userData.bone = bone; handle.visible = false; handle.renderOrder = 999; scene.add(handle); state.rigHandles.push(handle); }); }
function updateRigHandles() { state.rigHandles.forEach(handle => handle.userData.bone.getWorldPosition(handle.position)); }
function physicsPart(wrapper, item) { const bone = item.mesh.skeleton?.bones?.[wrapper.params?.boneIndex]; const name = `${wrapper.params?.name || ''} ${bone?.name || ''}`.toLowerCase(); if (/hair|髪|前髪|後髪/.test(name)) return 'hair'; if (/skirt|cloth|ribbon|dress|スカート|リボン|衣/.test(name)) return 'cloth'; return 'body'; }
function applyPhysicsSettings(item = state.active) { if (!item?.physics?.bodies || !globalThis.Ammo) return; const { stiffness, damping, gravity, parts } = state.physicsSettings; item.physics.setGravity(new THREE.Vector3(0, -98 * gravity, 0)); item.physics.bodies.forEach(wrapper => { const body = wrapper.body; if (!body) return; const enabled = parts[physicsPart(wrapper, item)]; body.setDamping(enabled ? damping : 1, enabled ? damping : 1); body.setRestitution(enabled ? stiffness : 0); }); }
function enablePhysics(item = state.active) { if (!item) return; ammoReady.then(Ammo => { const mmd = item.mesh.geometry?.userData?.MMD; if (!Ammo || !mmd?.rigidBodies?.length) { toast('このモデルには利用可能な物理剛体がありません'); return; } try { item.physics ||= new MMDPhysics(item.mesh, mmd.rigidBodies, mmd.constraints || [], { unitStep: 1 / 90, maxStepNum: 5 }); item.physics.reset(); applyPhysicsSettings(item); } catch (error) { console.warn(error); toast('物理を有効化できませんでした'); } }); }
function applyWind(item, time) { if (!item?.physics?.bodies || !globalThis.Ammo) return; const { wind, turbulence, parts } = state.physicsSettings; if (!wind && !turbulence) return; item.physics.bodies.forEach((wrapper, index) => { const part = physicsPart(wrapper, item); if ((part !== 'hair' && part !== 'cloth') || !parts[part]) return; const body = wrapper.body; if (!body) return; const gust = wind + Math.sin(time * 2.1 + index * 1.7) * turbulence * wind; const force = new Ammo.btVector3(gust, Math.sin(time * 3.7 + index) * turbulence * wind * .2, Math.cos(time * 1.3 + index) * turbulence * wind * .35); body.applyCentralForce(force); Ammo.destroy(force); }); }
function installMmdShader(material) { material.userData.mmdLabShader ||= { uSpecular: { value: 0.2 }, uWetness: { value: 0 }, uTextureStrength: { value: 1 } }; }
function applySkinShader() { const settings = state.skinSettings; state.models.forEach(item => item.mesh.traverse(node => { if (!node.isMesh || !node.material) return; (Array.isArray(node.material) ? node.material : [node.material]).forEach(material => { installMmdShader(material); const u = material.userData.mmdLabShader; u.uSpecular.value = settings.specular; u.uWetness.value = settings.wetness; u.uTextureStrength.value = settings.roughnessMap; }); })); }
function renderSceneModels() { const root = $('#models'); if (!state.models.length) { root.innerHTML = '<div class="empty">モデルを読み込むと<br/>ここに表示されます</div>'; $('#model-count').textContent = '0 models'; return; } root.innerHTML = ''; state.models.forEach((m, i) => { const row = document.createElement('button'); row.className = `asset ${m === state.active ? 'active' : ''}`; row.innerHTML = `<span>${String(i + 1).padStart(2, '0')}</span><div><b>${m.name}</b><small>Scene model</small></div>`; row.onclick = () => setActive(m); root.append(row); }); $('#model-count').textContent = `${state.models.length} models`; }
function morphMeshes(root) { const result = []; root?.traverse(node => { if (node.isMesh && node.morphTargetDictionary && node.morphTargetInfluences) result.push(node); }); return result; }
function renderMorphs() { const root = $('#morphs'), meshes = morphMeshes(state.active?.mesh); if (!meshes.length) { root.innerHTML = '<div class="empty">モデルを選択すると<br/>モーフが表示されます</div>'; return; } const groups = new Map(); meshes.forEach(mesh => Object.entries(mesh.morphTargetDictionary).forEach(([name, index]) => { if (!groups.has(name)) groups.set(name, []); groups.get(name).push({ mesh, index }); })); root.innerHTML = ''; [...groups.entries()].slice(0, 100).forEach(([name, bindings]) => { const value = bindings.reduce((n, x) => n + x.mesh.morphTargetInfluences[x.index], 0) / bindings.length; const row = document.createElement('div'); row.innerHTML = `<label>${name}<output>${Math.round(value * 100)}%</output></label><input type="range" min="0" max="1" step=".01" value="${value}">`; const input = row.querySelector('input'), output = row.querySelector('output'); input.oninput = () => { const v = +input.value; bindings.forEach(x => x.mesh.morphTargetInfluences[x.index] = v); output.textContent = `${Math.round(v * 100)}%`; }; root.append(row); }); }
function renderMaterials() { const root = $('#materials'); if (!state.active) { root.innerHTML = '<div class="empty">モデルを選択すると<br/>マテリアルが表示されます</div>'; return; } const entries = []; state.active.mesh.traverse(mesh => { if (!mesh.isMesh || !mesh.material) return; (Array.isArray(mesh.material) ? mesh.material : [mesh.material]).forEach((material, index) => entries.push({ mesh, material, index })); }); root.innerHTML = ''; entries.forEach(({ material }, index) => { const row = document.createElement('label'); row.className = 'check'; const label = material.name || material.map?.name || `Material ${String(index + 1).padStart(2, '0')}`; row.innerHTML = `<input type="checkbox" ${material.visible ? 'checked' : ''}><span>${label}</span>`; row.querySelector('input').onchange = e => { material.visible = e.target.checked; material.needsUpdate = true; }; root.append(row); }); if (!entries.length) root.innerHTML = '<div class="empty">マテリアルが見つかりません</div>'; }
function clearModels() { state.models.forEach(({ mesh }) => { scene.remove(mesh); mesh.traverse(node => { node.geometry?.dispose(); if (node.material) (Array.isArray(node.material) ? node.material : [node.material]).forEach(m => m.dispose()); }); }); state.models = []; state.active = null; state.mixers = []; state.duration = 0; renderSceneModels(); renderMorphs(); }
function applyHDR(texture, label, notify = true) { const env = pmrem.fromEquirectangular(texture).texture; texture.dispose(); state.environment?.dispose(); state.environment = env; scene.environment = env; scene.environmentIntensity = state.environmentStrength; scene.background = new THREE.Color(0xe9edf2); $('#show-hdri').checked = false; $('#hdri-name').textContent = label; if (notify) toast(`HDRI: ${label}`); }
function loadHDR(file) { if (!file) return; setNotice('LOADING HDRI…'); new RGBELoader().load(url(file), texture => { applyHDR(texture, file.name); setNotice(); }, undefined, () => { setNotice(); toast('HDRI の読み込みに失敗しました'); }); }
new RGBELoader().load('https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/white_studio_05_1k.hdr', texture => applyHDR(texture, 'Poly Haven — White Studio 05 (CC0)', false), undefined, () => { $('#hdri-name').textContent = '標準 HDRI を読み込めませんでした'; });

function resize() { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); } addEventListener('resize', resize);
let tick = 0, last = performance.now(); function animate() { requestAnimationFrame(animate); const dt = Math.min(clock.getDelta(), .1); if (state.playing) { state.elapsed += dt; state.mixers.forEach(x => x.mixer.update(dt)); if (state.physics) state.models.forEach(x => { applyWind(x, state.elapsed); x.physics?.update(dt); }); } if (state.duration) { if (state.elapsed > state.duration) { if (state.loop) state.elapsed %= state.duration; else state.playing = false; } $('#timeline').value = state.elapsed / state.duration; $('#timecode').textContent = `${String(Math.floor(state.elapsed / 60)).padStart(2, '0')}:${(state.elapsed % 60).toFixed(1).padStart(4, '0')}`; } updateRigHandles(); controls.update(); state.outline ? effect.render(scene, camera) : renderer.render(scene, camera); if (++tick % 20 === 0) { const now = performance.now(); $('#fps').textContent = `${Math.round(20000 / (now - last))} FPS`; last = now; } } animate();

$('#open-models').onclick = () => $('#models-file').click(); $('#open-motions').onclick = () => $('#motions-file').click(); $('#open-folder').onclick = () => $('#folder').click();
$('#models-file').onchange = async e => importAssets(e.target.files, true); $('#motions-file').onchange = async e => importAssets(e.target.files, false); $('#folder').onchange = async e => importAssets(e.target.files, false); $('#clear-models').onclick = clearModels;
$('#play').onclick = e => { state.playing = !state.playing; e.currentTarget.textContent = state.playing ? '❚❚' : '▶'; }; $('#loop').onclick = e => { state.loop = !state.loop; e.currentTarget.classList.toggle('active', state.loop); }; $('#timeline').oninput = e => { if (!state.duration) return; state.elapsed = +e.target.value * state.duration; state.mixers.forEach(x => x.mixer.setTime(state.elapsed)); };
$('#toon-outline').onchange = e => state.outline = e.target.checked; $('#outline').oninput = e => { effect.defaultThickness = +e.target.value / 100; $('#outline-value').textContent = e.target.value; }; $('#exposure').oninput = e => { renderer.toneMappingExposure = +e.target.value; $('#exposure-value').textContent = e.target.value; };
$('#open-hdri').onclick = () => $('#hdri').click(); $('#hdri').onchange = e => loadHDR(e.target.files[0]); $('#env-intensity').oninput = e => { state.environmentStrength = +e.target.value; scene.environmentIntensity = state.environmentStrength; $('#env-value').textContent = state.environmentStrength.toFixed(2); }; $('#show-hdri').onchange = e => scene.background = e.target.checked && state.environment ? state.environment : new THREE.Color(0xe9edf2); $('#grid').onchange = e => grid.visible = e.target.checked; $('#shadows').onchange = e => renderer.shadowMap.enabled = e.target.checked; $('#reset-morph').onclick = () => { morphMeshes(state.active?.mesh).forEach(m => m.morphTargetInfluences.fill(0)); renderMorphs(); };
$$('.tabs button').forEach(button => button.onclick = () => { $$('.tabs button').forEach(x => x.classList.toggle('active', x === button)); $$('.tab-content').forEach(x => x.classList.toggle('active', x.id === `${button.dataset.tab}-tab`)); }); $$('[data-camera]').forEach(button => button.onclick = () => { camera.position.fromArray({ front: [0, 4.8, 12], threequarter: [8, 5.4, 12], wide: [13, 9, 18] }[button.dataset.camera]); controls.update(); });
['dragenter', 'dragover'].forEach(type => addEventListener(type, e => { e.preventDefault(); $('#dropzone').classList.add('show'); })); ['dragleave', 'drop'].forEach(type => addEventListener(type, e => { e.preventDefault(); if (type === 'dragleave' && e.relatedTarget) return; $('#dropzone').classList.remove('show'); })); addEventListener('drop', e => importAssets(e.dataTransfer.files, true));
$('#physics').onchange = e => { state.physics = e.target.checked; if (state.physics) enablePhysics(); };
[['stiffness', 'stiffness'], ['damping', 'damping'], ['gravity', 'gravity']].forEach(([id, key]) => { $(`#${id}`).oninput = e => { state.physicsSettings[key] = +e.target.value; $(`#${id}-value`).textContent = (+e.target.value).toFixed(2); applyPhysicsSettings(); }; });
$$('.physics-part').forEach(input => input.onchange = e => { state.physicsSettings.parts[e.target.dataset.part] = e.target.checked; applyPhysicsSettings(); });
$$('[data-physics-preset]').forEach(button => button.onclick = () => { const preset = { hair: { stiffness: .72, damping: .12, gravity: .9 }, cloth: { stiffness: .85, damping: .07, gravity: 1.15 }, body: { stiffness: .5, damping: .2, gravity: 1 } }[button.dataset.physicsPreset]; Object.assign(state.physicsSettings, preset); ['stiffness', 'damping', 'gravity'].forEach(key => { $(`#${key}`).value = preset[key]; $(`#${key}-value`).textContent = preset[key].toFixed(2); }); applyPhysicsSettings(); });
[['wind', 'wind'], ['turbulence', 'turbulence']].forEach(([id, key]) => { $(`#${id}`).oninput = e => { state.physicsSettings[key] = +e.target.value; $(`#${id}-value`).textContent = (+e.target.value).toFixed(2); }; });
[['specular', 'specular'], ['wetness', 'wetness'], ['roughness-map', 'roughnessMap']].forEach(([id, key]) => { $(`#${id}`).oninput = e => { state.skinSettings[key] = +e.target.value; $(`#${id}-value`).textContent = (+e.target.value).toFixed(2); applySkinShader(); }; });
$('#rig-edit').onchange = e => { state.rigHandles.forEach(h => h.visible = e.target.checked); transform.visible = e.target.checked; if (!e.target.checked) transform.detach(); };
$('#show-all-materials').onclick = () => { state.active?.mesh.traverse(mesh => { if (!mesh.isMesh || !mesh.material) return; (Array.isArray(mesh.material) ? mesh.material : [mesh.material]).forEach(material => material.visible = true); }); renderMaterials(); };
canvas.addEventListener('pointerdown', e => { if (!$('#rig-edit').checked) return; const r = canvas.getBoundingClientRect(); pointer.set((e.clientX - r.left) / r.width * 2 - 1, -(e.clientY - r.top) / r.height * 2 + 1); raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(state.rigHandles.filter(h => h.visible), false)[0]; if (hit) transform.attach(hit.object.userData.bone); });
refreshAssets();
