import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { MMDLoader } from 'three/addons/loaders/MMDLoader.js';
import { MMDAnimationHelper } from 'three/addons/animation/MMDAnimationHelper.js';
import { OutlineEffect } from 'three/addons/effects/OutlineEffect.js';

const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
const state = { models: [], active: null, playing: true, loop: true, flow: true, physics: true, flowStrength: .35, mixers: [], duration: 0, elapsed: 0 };
const clock = new THREE.Clock(), scene = new THREE.Scene(), canvas = $('#scene');
scene.background = new THREE.Color(0x080b14); scene.fog = new THREE.FogExp2(0x080b14, .035);
const camera = new THREE.PerspectiveCamera(38, innerWidth / innerHeight, .1, 1000); camera.position.set(8, 5.4, 12);
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.1;
const effect = new OutlineEffect(renderer, { defaultThickness: .0045, defaultColor: [0.1, 0.07, 0.18], defaultAlpha: .85, defaultKeepAlive: true });
const controls = new OrbitControls(camera, canvas); controls.target.set(0, 4, 0); controls.enableDamping = true; controls.dampingFactor = .06; controls.maxPolarAngle = Math.PI * .48;
const hemi = new THREE.HemisphereLight(0xbac6ff, 0x111022, 2.5); scene.add(hemi); const key = new THREE.DirectionalLight(0xffd6ef, 3.5); key.position.set(4, 10, 5); key.castShadow = true; key.shadow.mapSize.set(2048, 2048); key.shadow.camera.left = key.shadow.camera.bottom = -15; key.shadow.camera.right = key.shadow.camera.top = 15; scene.add(key); const rim = new THREE.PointLight(0x896dff, 30, 25); rim.position.set(-6, 5, -5); scene.add(rim);
const floor = new THREE.Mesh(new THREE.CircleGeometry(20, 64), new THREE.MeshStandardMaterial({ color: 0x111426, roughness: .72, metalness: .25 })); floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor); const grid = new THREE.GridHelper(32, 32, 0x5f4e91, 0x262440); grid.position.y = .012; scene.add(grid);
const loader = new MMDLoader(); const helper = new MMDAnimationHelper({ afterglow: 2.0, resetPhysicsOnLoop: true });
function toast(m){ $('#toast').textContent=m; $('#toast').classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2500); }
function ext(file){ return file.name.split('.').pop().toLowerCase(); }
function objectURL(file){ return URL.createObjectURL(file); }
async function loadFiles(files){
  const all=[...files], models=all.filter(f=>['pmx','pmd'].includes(ext(f))), motions=all.filter(f=>ext(f)==='vmd'), poses=all.filter(f=>ext(f)==='vpd');
  if(!models.length && !motions.length && !poses.length){toast('対応ファイルを選択してください');return;}
  $('#notice').textContent='LOADING ASSETS…';
  for(const file of models){ await loadModel(file); }
  for(const file of motions){ await loadMotion(file); }
  for(const file of poses){ await loadPose(file); }
  $('#notice').textContent='READY — LOCAL MODE';
}
function loadModel(file){ return new Promise((resolve,reject)=>loader.load(objectURL(file), mesh=>{ mesh.name=file.name; mesh.castShadow=mesh.receiveShadow=true; mesh.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;}}); const offset=state.models.length*2.7; mesh.position.x=offset-(Math.max(state.models.length,1)-1)*1.35; scene.add(mesh); const item={mesh,file,name:file.name,phase:Math.random()*6.2,base:mesh.position.clone()}; state.models.push(item); setActive(item); renderModels(); frameModel(mesh); toast(`${file.name} を読み込みました`); resolve(); },undefined,e=>{console.error(e);toast(`${file.name} を読めませんでした`);resolve();})); }
function loadMotion(file){ return new Promise(resolve=>{ const targets=state.models.map(x=>x.mesh); if(!targets.length){toast('先にモデルを読み込んでください');return resolve();} loader.loadAnimation(objectURL(file),targets, animation=>{ targets.forEach((mesh,i)=>{const clip=Array.isArray(animation)?animation[i]:animation; if(clip){const mixer=new THREE.AnimationMixer(mesh); const action=mixer.clipAction(clip).play(); action.setLoop(THREE.LoopRepeat,Infinity); state.mixers.push({mixer,action,clip}); state.duration=Math.max(state.duration,clip.duration);}}); toast(`VMD: ${file.name}`); resolve(); },undefined,()=>{toast('VMD の読み込みに失敗しました');resolve();}); }); }
function loadPose(file){ if(!state.active){toast('先にモデルを選択してください');return Promise.resolve();} return new Promise(resolve=>loader.loadVPD(objectURL(file),false,vpd=>{loader.poseAsVpd(state.active.mesh,vpd);toast(`VPD: ${file.name}`);resolve();},undefined,()=>{toast('VPD の読み込みに失敗しました');resolve();})); }
function frameModel(mesh){ const box=new THREE.Box3().setFromObject(mesh), size=box.getSize(new THREE.Vector3()), center=box.getCenter(new THREE.Vector3()); controls.target.copy(center); camera.position.copy(center).add(new THREE.Vector3(size.y*.62,size.y*.28,size.y*1.45)); controls.update(); }
function setActive(item){state.active=item; renderModels(); renderMorphs();}
function renderModels(){const root=$('#models');if(!state.models.length){root.innerHTML='<div class="empty">モデルをドロップ<br/>して開始</div>';return;}root.innerHTML='';state.models.forEach((m,i)=>{const el=document.createElement('button');el.className='asset '+(m===state.active?'active':'');el.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><div><b>${m.name}</b><small>${m.mesh.geometry?.attributes.position?.count?.toLocaleString()||'—'} vertices</small></div>`;el.onclick=()=>setActive(m);root.append(el);});$('#model-count').textContent=`${state.models.length} model${state.models.length!==1?'s':''}`;}
function renderMorphs(){const root=$('#morphs'), mesh=state.active?.mesh;if(!mesh?.morphTargetDictionary){root.innerHTML='<div class="empty">このモデルには<br/>操作可能なモーフがありません</div>';return;}const dict=mesh.morphTargetDictionary, infl=mesh.morphTargetInfluences;root.innerHTML='';Object.entries(dict).slice(0,48).forEach(([name,index])=>{const wrap=document.createElement('div');wrap.innerHTML=`<label>${name}<output>${Math.round(infl[index]*100)}%</output></label><input type="range" min="0" max="1" step=".01" value="${infl[index]}">`;const input=wrap.querySelector('input'),out=wrap.querySelector('output');input.oninput=()=>{infl[index]=+input.value;out.textContent=`${Math.round(+input.value*100)}%`;};root.append(wrap);});}
function clearModels(){state.models.forEach(({mesh})=>{scene.remove(mesh);mesh.traverse(o=>{o.geometry?.dispose();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(x=>x.dispose());}})});state.models=[];state.active=null;state.mixers=[];state.duration=0;renderModels();renderMorphs();}
function procedural(item,t){const root=item.mesh; const bones=[];root.traverse(o=>{if(o.isBone)bones.push(o)}); const find=(q)=>bones.find(b=>b.name.toLowerCase().includes(q)); const s=state.flowStrength, wave=Math.sin(t*1.35+item.phase)*s; const spine=find('上半身')||find('spine'), head=find('頭')||find('head'), larm=find('左腕')||find('leftarm'), rarm=find('右腕')||find('rightarm'); if(spine)spine.rotation.z=wave*.025;if(head)head.rotation.y=Math.sin(t*.7+item.phase)*s*.035;if(larm)larm.rotation.z=wave*.06;if(rarm)rarm.rotation.z=-wave*.06;root.position.y=item.base.y+Math.sin(t*1.35+item.phase)*s*.035;}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}addEventListener('resize',resize);
let frameCount=0,lastFps=performance.now();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.1);if(state.playing){state.elapsed+=dt;state.mixers.forEach(x=>x.mixer.update(dt));if(state.flow)state.models.forEach(m=>procedural(m,state.elapsed));}if(state.duration){if(state.elapsed>state.duration){if(state.loop)state.elapsed%=state.duration;else state.playing=false;}$('#timeline').value=state.elapsed/state.duration;$('#timecode').textContent=`${String(Math.floor(state.elapsed/60)).padStart(2,'0')}:${(state.elapsed%60).toFixed(1).padStart(4,'0')}`;}controls.update();effect.render(scene,camera);if(++frameCount%20===0){const now=performance.now();$('#fps').textContent=`${Math.round(20000/(now-lastFps))} FPS`;lastFps=now;}}
animate();
$('#open-files').onclick=()=>$('#files').click();$('#open-folder').onclick=()=>$('#folder').click();$('#files').onchange=e=>loadFiles(e.target.files);$('#folder').onchange=e=>loadFiles(e.target.files);$('#clear-models').onclick=clearModels;
$('#play').onclick=e=>{state.playing=!state.playing;e.currentTarget.textContent=state.playing?'❚❚':'▶';};$('#loop').onclick=e=>{state.loop=!state.loop;e.currentTarget.classList.toggle('active',state.loop)};$('#timeline').oninput=e=>{if(!state.duration)return;state.elapsed=+e.target.value*state.duration;state.mixers.forEach(x=>x.mixer.setTime(state.elapsed));};$('#flow').onchange=e=>state.flow=e.target.checked;$('#physics').onchange=e=>{state.physics=e.target.checked;toast(e.target.checked?'Physics simulation enabled':'Physics simulation disabled')};$('#flow-strength').oninput=e=>{state.flowStrength=e.target.value/100;$('#flow-value').textContent=e.target.value+'%'};$('#outline').oninput=e=>{effect.defaultThickness=+e.target.value/100;$('#outline-value').textContent=e.target.value};$('#exposure').oninput=e=>{renderer.toneMappingExposure=+e.target.value;$('#exposure-value').textContent=e.target.value};$('#grid').onchange=e=>grid.visible=e.target.checked;$('#shadows').onchange=e=>renderer.shadowMap.enabled=e.target.checked;$('#reset-morph').onclick=()=>{const inf=state.active?.mesh.morphTargetInfluences;if(inf){inf.fill(0);renderMorphs();}};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-content').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab+'-tab'));});$$('[data-camera]').forEach(b=>b.onclick=()=>{const p={front:[0,4.8,12],threequarter:[8,5.4,12],wide:[13,9,18]}[b.dataset.camera];camera.position.fromArray(p);controls.update();});
['dragenter','dragover'].forEach(t=>addEventListener(t,e=>{e.preventDefault();$('#dropzone').classList.add('show')}));['dragleave','drop'].forEach(t=>addEventListener(t,e=>{e.preventDefault();if(t==='dragleave'&&e.relatedTarget)return;$('#dropzone').classList.remove('show')}));addEventListener('drop',e=>loadFiles(e.dataTransfer.files));
