export const BACKGROUND_NAME = '';
export const BACKGROUND_SHA256 = '';
export const BACKGROUND_UNCOMPRESSED_BYTES = 0;
export const BACKGROUND_GZIP_BASE64_CHUNKS = [] as const;
export const BACKGROUND_PROXY_SHA256 = '';
export const BACKGROUND_PROXY_UNCOMPRESSED_BYTES = 0;
export const BACKGROUND_PROXY_GZIP_BASE64 = '';
